name: Deploy FA Mainnet
run-name: ${{ github.actor }} is deploying FA Mainnet
on:
  push:
    branches:
      - "fa_mainnet"
jobs:
  deploy:
    runs-on: fa_mainnet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          docker compose --project-name fa_mainnet -f docker-compose-fa-mainnet.yaml down || true
          docker rmi fa_mainnet || true
          echo "${{ secrets.ENV_FA_MAINNET }}" >> config.yaml
          docker compose --project-name fa_mainnet -f docker-compose-fa-mainnet.yaml up -d